"""expand product system

Revision ID: 3f1e1898e6be
Revises: b3264b06baf6
Create Date: 2026-05-29 15:14:54.755282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f1e1898e6be'
down_revision: Union[str, Sequence[str], None] = 'b3264b06baf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('recipe_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('lead_time_hours', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('max_daily_quantity', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('order_cutoff_hours', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('available_days', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'available_days')
    op.drop_column('products', 'order_cutoff_hours')
    op.drop_column('products', 'max_daily_quantity')
    op.drop_column('products', 'lead_time_hours')
    op.drop_column('products', 'recipe_id')
    # ### end Alembic commands ###
