"""expand inventory intelligence

Revision ID: 6fce9f729e9c
Revises: 9a8b53ccd36a
Create Date: 2026-05-29 19:26:45.353161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fce9f729e9c'
down_revision: Union[str, Sequence[str], None] = '9a8b53ccd36a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('item_name', sa.String(), nullable=False))
    op.add_column('inventory', sa.Column('category', sa.String(), nullable=False))
    op.add_column('inventory', sa.Column('projected_depletion', sa.Float(), nullable=False))
    op.add_column('inventory', sa.Column('low_stock', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'low_stock')
    op.drop_column('inventory', 'projected_depletion')
    op.drop_column('inventory', 'category')
    op.drop_column('inventory', 'item_name')
    # ### end Alembic commands ###
