"""expand production engine

Revision ID: 9a8b53ccd36a
Revises: a81e9947d4b3
Create Date: 2026-05-29 18:58:30.050417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a8b53ccd36a'
down_revision: Union[str, Sequence[str], None] = 'a81e9947d4b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_runs', sa.Column('task_name', sa.String(), nullable=False))
    op.add_column('production_runs', sa.Column('scheduled_time', sa.String(), nullable=False))
    op.add_column('production_runs', sa.Column('linked_order_id', sa.Integer(), nullable=True))
    op.drop_column('production_runs', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_runs', sa.Column('name', sa.VARCHAR(), nullable=False))
    op.drop_column('production_runs', 'linked_order_id')
    op.drop_column('production_runs', 'scheduled_time')
    op.drop_column('production_runs', 'task_name')
    # ### end Alembic commands ###
