"""expand order system

Revision ID: a81e9947d4b3
Revises: 3f1e1898e6be
Create Date: 2026-05-29 15:46:31.049083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a81e9947d4b3'
down_revision: Union[str, Sequence[str], None] = '3f1e1898e6be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_name', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('product_name', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('pickup_date', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'pickup_date')
    op.drop_column('orders', 'quantity')
    op.drop_column('orders', 'product_name')
    op.drop_column('orders', 'customer_name')
    # ### end Alembic commands ###
