"""expand customer system

Revision ID: f6e545f3e006
Revises: 6fce9f729e9c
Create Date: 2026-05-29 20:24:33.639339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6e545f3e006'
down_revision: Union[str, Sequence[str], None] = '6fce9f729e9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('preferred_pickup_day', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('favorite_products', sa.Text(), nullable=True))
    op.add_column('customers', sa.Column('bake_preferences', sa.Text(), nullable=True))
    op.add_column('customers', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('customers', sa.Column('last_order_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'last_order_date')
    op.drop_column('customers', 'notes')
    op.drop_column('customers', 'bake_preferences')
    op.drop_column('customers', 'favorite_products')
    op.drop_column('customers', 'preferred_pickup_day')
    # ### end Alembic commands ###
